export const projects = [
    {   
        id: 1,
        name: 'Helpdesk',
        description: 'Aplicação Helpdesk com um CRUD de chamados, técnicos e clientes.',
        video: '../../../assets/videos/helpdesk.mp4',
        image:'../../../assets/images/helpdesk.png',
        url: 'https://github.com/kaioruan/helpdesk-java-angular',
        backend: 'Java, Spring Boot, Maven, JPA/Hibernate, banco de dados H2 e MySQL.',
        frontend: 'Typescript, Angular, HTML e CSS.',
    },
    {   
        id: 2,
        name: 'App-delivery',
        description: 'Aplicação Fullstack sobre um delivery de bebidas.',
        video: '../../../assets/videos/app-delivery.mp4',
        image:'../../../assets/images/app-delivery.png',
        url: 'https://github.com/kaioruan/app-delivery',
        backend: 'Javascript, React, Context API, CSS.',
        frontend: 'Javascript, NodeJS, Testes de Integração, banco de dados relacional MySQL.',
    },
    {
        id: 3,
        name: 'MyRecipe-app',
        description: 'Aplicação de receitas culinárias voltada pra mobile.',
        video: '../../../assets/videos/app-receitas.mp4',
        image:'../../../assets/images/app-receitas.png',
        url: 'https://github.com/kaioruan/myRecipe-app',
        backend:'',
        frontend: 'Javascript, React, Context API e Testes Unitários.',
    },
    {
      id: 4,
      name: 'Trivia',
      description: 'Aplicação Frontend de um jogo de Perguntas',
      video: '../../../assets/videos/trivia.mp4',
      image:'../../../assets/images/trivia.png',
      url: 'https://github.com/kaioruan/project-trivia-react-redux',
      backend:'',
      frontend: 'Javascript, React, Redux e Testes Unitários.',
  },
]
