export const projects = [
    {   
        id: 1,
        name: 'Helpdesk',
        description: 'Aplicação Helpdesk onde é possível realizar Cadastros, Atualizações, Leitura e Remoção de Clientes e Técnicos em uma plataforma Helpdesk e também criação de Chamados, Atualização e Visualização.',
        video: '../../../assets/videos/helpdesk.mp4',
        image:'../../../assets/images/helpdesk.png',
        url: 'https://github.com/kaioruan/helpdesk-java-angular',
        backend: 'Java, Spring Boot, Maven, JPA/Hibernate, banco de dados H2 e MySQL.',
        frontend: 'Typescript, Angular, HTML e CSS.',
    },
    {   
        id: 2,
        name: 'App-delivery',
        description: 'Aplicação Fullstack sobre um delivery de bebidas. Foi construído de forma que tem 3 tipos de acesso, um acesso sendo Administrativo para gerenciar os conteúdos e adicionar ou remover novos vendedores, acesso de Vendedor onde é realizado os controles de cada venda vinculada ao vendedor e o acesso de cliente para realização de compras.',
        video: '../../../assets/videos/app-delivery.mp4',
        image:'../../../assets/images/app-delivery.png',
        url: 'https://github.com/kaioruan/app-delivery',
        backend: 'Javascript, React, Context API, CSS, RTL para elaboração de testes, Joi, Bcrypt, JWT e Dotenv.',
        frontend: 'Javascript, NodeJS, Sequelize, Express, Mocha, Chai e Sinon para testes de integração, banco de dados relacional MySQL.',
    },
    {
        id: 3,
        name: 'MyRecipe-app',
        description: 'Aplicação de receitas culinárias voltada pra mobile.',
        video: '../../../assets/videos/app-receitas.mp4',
        image:'../../../assets/images/app-receitas.png',
        url: 'https://github.com/kaioruan/myRecipe-app',
        backend:'',
        frontend: 'Javascript, React, Context API e Testes Unitários através da biblioteca RTL.',
    },
    {
      id: 4,
      name: 'Trivia',
      description: 'Aplicação Frontend de um jogo de Perguntas',
      video: '../../../assets/videos/trivia.mp4',
      image:'../../../assets/images/trivia.png',
      url: 'https://github.com/kaioruan/project-trivia-react-redux',
      backend:'',
      frontend: 'Javascript, React, Redux, Arquitetura de Software, Componentização e elaboração de Testes Unitários através da biblioteca RTL.',
  },
]
